DROP DATABASE IF EXISTS quantum;
CREATE DATABASE quantum;
USE quantum;

CREATE TABLE tipo_documento(
	id INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    tipo_documento VARCHAR(100)
);
CREATE TABLE tipo_comprobante(
	id INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    tipo_comprobante VARCHAR(100)
);
CREATE TABLE tipo_permiso (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    tipo_permiso VARCHAR(50)
);
CREATE TABLE tipo_contrato (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    tipo_contrato VARCHAR(50)
);
CREATE TABLE estado_contrato(
	id INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    estado VARCHAR(50)
);
CREATE TABLE estado_permiso (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    tipo_estado VARCHAR(12)
);
CREATE TABLE estado_jefe (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    tipo VARCHAR(10)
);
CREATE TABLE jornada (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    tipo_jornada VARCHAR (255)
);
CREATE TABLE arl (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50)
);
CREATE TABLE rol (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50)
);
CREATE TABLE area (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50)
);
CREATE TABLE eps (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50)
);
/*CREATE TABLE soporte (
	id INTEGER(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(100),
    url VARCHAR(255)
);*/
CREATE TABLE estado_civil (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    tipo_estado VARCHAR(30)
);
CREATE TABLE horario (
	id INTEGER(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    hora_ingreso TIME(6),
    hora_salida TIME(6)
);
CREATE TABLE parentesco (
	id TINYINT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    tipo_estado VARCHAR(30)
);


